-- Execute no SQL Editor do Supabase.
create type public.user_role as enum ('member', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  role public.user_role not null default 'member',
  created_at timestamptz not null default now()
);

create table public.courts (
  id bigint generated by default as identity primary key,
  name text not null,
  surface text not null default 'Saibro',
  location text not null default 'Externa',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.availability (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null check (start_time in ('06:00', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00', '20:00')),
  end_time time not null check (end_time = start_time + interval '2 hours'),
  unique (court_id, day_of_week, start_time)
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id),
  user_id uuid not null references auth.users(id),
  booking_date date not null,
  start_time time not null check (start_time in ('06:00', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00', '20:00')),
  end_time time not null check (end_time = start_time + interval '2 hours'),
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
  created_at timestamptz not null default now(),
  unique (court_id, booking_date, start_time)
);

-- Cria o perfil automaticamente quando uma conta é criada no Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email), new.email);
  if lower(new.email) = 'programacaotennis@gmail.com' then
    update public.profiles set role = 'admin' where id = new.id;
  end if;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Função protegida para as políticas não dependerem de dados enviados pelo navegador.
create or replace function public.is_admin()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.courts enable row level security;
alter table public.availability enable row level security;
alter table public.bookings enable row level security;

create policy "profiles are visible to authenticated users" on public.profiles for select to authenticated using (true);
create policy "admins manage profile roles" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "members can view active courts" on public.courts for select to authenticated using (active = true);
create policy "members can view availability" on public.availability for select to authenticated using (true);
create policy "members view their bookings" on public.bookings for select to authenticated using (user_id = auth.uid());
create policy "members create their bookings" on public.bookings for insert to authenticated with check (user_id = auth.uid());
create policy "admins manage courts" on public.courts for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage availability" on public.availability for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins view all bookings" on public.bookings for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "users cancel their bookings" on public.bookings for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

insert into public.courts (name, surface, location)
values
  ('Quadra 1', 'Saibro', 'Externa'),
  ('Quadra 2', 'Saibro', 'Externa'),
  ('Quadra 3', 'Rápida', 'Coberta'),
  ('Quadra 4', 'Saibro', 'Externa');

-- Disponibilidade padrão: todos os dias, das 06:00 às 22:00 em blocos de 2 horas.
insert into public.availability (court_id, day_of_week, start_time, end_time)
select courts.id, days.day_of_week, slots.start_time, slots.start_time + interval '2 hours'
from public.courts
cross join generate_series(0, 6) as days(day_of_week)
cross join (values
  (time '06:00'), (time '08:00'), (time '10:00'), (time '12:00'),
  (time '14:00'), (time '16:00'), (time '18:00'), (time '20:00')
) as slots(start_time)
on conflict (court_id, day_of_week, start_time) do nothing;

-- O cadastro com programacaotennis@gmail.com recebe admin automaticamente.